export const ValidationMessageConfigEN = {
    min: 'Please enter a value of at least {0}',
    max: 'Please fill in values up to {0}',
    required: 'Please fill',
    requiredTrue: 'Please fill',
    requiredSelect: 'Please choose',
    email: 'Please enter the email correctly.',
    minlength: 'Please enter at least letters. {0} character',
    maxlength: 'Please enter no more than characters. {0} character',
    pattern: 'Please fill out to match the specified format.',
    taxNoInvalid: 'Invalid ID / Tax ID number format',
    passwordMismatch: 'Please specify password',
    invalidOtp: 'Invalid OTP code',
    E02PND52008: 'Please check that the 13 digit number is correct.',
    bsDate: 'You have incorrectly recorded your birth date. Please check.',

    CONF_PASS:'Please enter the password that matches with the password confirmation.',
    mismatchedPasswords:"Please enter the password that matches with the password confirmation.",
    mismatchedEmail:"Your email and your manager's email cannot be the same.",
}